openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Inferred Url
tags:
  - name: environments-controller
    description: Environments Controller
paths:
  /api/tdm/environments/{environmentId}/systems/lazy:
    get:
      tags:
        - environments-controller
      summary: getLazySystems
      operationId: getLazySystems
      parameters:
        - name: environmentId
          in: path
          description: environmentId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LazySystem'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/tdm/envs/reset/caches:
    get:
      tags:
        - environments-controller
      summary: resetCaches
      operationId: resetCaches
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/tdm/projects/lazy:
    get:
      tags:
        - environments-controller
      summary: getProjects
      operationId: getProjects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LazyProject'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/tdm/projects/{projectId}/environments/lazy:
    get:
      tags:
        - environments-controller
      summary: getLazyEnvironments
      operationId: getLazyEnvironments
      parameters:
        - name: projectId
          in: path
          description: projectId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LazyEnvironment'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/tdm/projects/{projectId}/environments/lazy/refresh:
    get:
      tags:
        - environments-controller
      summary: getLazyEnvironmentsRefresh
      operationId: getLazyEnvironmentsRefresh
      parameters:
        - name: projectId
          in: path
          description: projectId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LazyEnvironment'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    LazyEnvironment:
      title: LazyEnvironment
      type: object
      properties:
        created:
          type: string
        createdBy:
          type: string
        description:
          type: string
        id:
          type: string
          format: uuid
        modified:
          type: string
        modifiedBy:
          type: string
        name:
          type: string
        projectId:
          type: string
          format: uuid
        systems:
          type: array
          items:
            type: string
    LazyProject:
      title: LazyProject
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    LazySystem:
      title: LazySystem
      type: object
      properties:
        connections:
          type: array
          items:
            type: string
        created:
          type: string
        createdBy:
          type: string
        description:
          type: string
        environmentIds:
          type: array
          items:
            type: string
            format: uuid
        id:
          type: string
          format: uuid
        modified:
          type: string
        modifiedBy:
          type: string
        name:
          type: string
