PAAS_PLATFORM: "KUBERNETES"
DOCKER_TAG: ""
# Deployment Config/Service type
SERVICE_TYPE: "ATP3"
SWAGGER_ENABLED: "false"
CONTENT_SECURITY_POLICY: "*"
ACTIVE_PROFILES_SPRING: "disable-security"
SERVICE_NAME: "atp3-tdm-be"
SERVICE_PORT_TYPE: "ClusterIP"
# Logging
GRAYLOG_HOST: "udp:graylog-service.example.com"
GRAYLOG_ON: "true"
GRAYLOG_PORT: "12201"
# Profiler
PROFILER_ENABLED: "false"
REMOTE_DUMP_HOST: "esc-collector-service.profiler.svc"
REMOTE_DUMP_PORT: "1710"
# Keycloak integration
KEYCLOAK_ENABLED: "false"
ENCRYPT: "dev"
ATP_CRYPTO_KEY: ""
ATP_CRYPTO_PRIVATE_KEY: ""
KEYCLOAK_AUTH_URL: ""
KEYCLOAK_REALM: "atp3"
# Mail sender
MAIL_SENDER_ENABLE: "false"
MAIL_SENDER_ENDPOINT: "/api/v1/mail-sender/mail/send"
MAIL_SENDER_PORT: "8080"
MAIL_SENDER_URL: ""
# Security Context properties
SECURITY_CONTEXT_ENABLED: false
# Host of Eureka server
SERVICE_REGISTRY_URL: ""
# Zipkin settings
ZIPKIN_ENABLE: "false"
ZIPKIN_PROBABILITY: "1.0"
ZIPKIN_URL: "http://zipkin.zipkin.svc:9411"
# Feign settings
FEIGN_CONNECT_TIMEOUT: "300000"
FEIGN_READ_TIMEOUT: "300000"
FEIGN_ATP_MAILSENDER_URL: ""
FEIGN_ATP_MAILSENDER_NAME: "ATP-MAIL-SENDER"
FEIGN_ATP_MAILSENDER_ROUTE: "api/atp-mail-sender/v1"
FEIGN_ATP_HIGHCHARTS_NAME: "ATP-CHARTS"
FEIGN_ATP_HIGHCHARTS_ROUTE: "api/atp-charts/v1"
FEIGN_ATP_HIGHCHARTS_URL: ""
# EnvGene configuration
ENVGENE_GIT_REPO_URL: ""
ENVGENE_GIT_REPO_TOKEN: ""
ENVGENE_GIT_REPO_BRANCH: ""
ENVGENE_GIT_REPO_DEPLOYMENT_PATH: "effective-set/deployment"
ENVGENE_GIT_REPO_NC_APP_PATH: "atp/atp3-playwright-runner"
ENVGENE_GIT_REPO_CREDENTIALS_PATH: "values/credentials.yaml"
ENVGENE_GIT_REPO_DEPLOYMENT_PARAMETERS_PATH: "values/deployment-parameters.yaml"

atp3tdm:
  externalQueryDefaultTimeout: "1800"
  externalQueryMaxTimeout: "1800"
  projectInfoEndpoint: "/api/v1/users/projects"
  gitProjectsInfo: {}
  atpInternalGatewayEnabled: "false"
  atpServicePath: "/api/atp-tdm/v1/**"
  atpServicePublic: "false"
  environmentsCacheDurations: "15"
  environmentsSpringCacheType: "GENERIC"
  eurekaClientEnabled: "false"
  fromEmailAddress: "tdm-tool-service@example.com"
  identityProviderUrl: ""
  jmxEnable: "true"
  jmxPort: "3000"
  jmxRmiPort: "3001"
  serviceEntitiesMigrationEnabled: 'false'
  keycloakClientName: "atp-tdm"
  keycloakSecret: ""
  localeResolver: "en"
  maxFileSize: "100MB"
  maxRequestSize: "100MB"
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  containerSecurityContext: {}
  h2DbAddr: "database"
  h2DbProperty: "MODE=PostgreSQL"
  tdmDb: ""
  tdmDbPassword: ""
  tdmDbUser: ""
  terminationPolicy: "Redirect"
  # Liquibase properties
  liquibaseEnabled: "false"
  liquibaseLaunchEnabled: "true"
  lockDefaultDurationSec: "60"
  lockRetryTimeoutSec: "10800"
  lockRetryPaceSec: "3"
  atpHttpLogging: 'true'
  atpHttpLoggingHeaders: 'true'
  atpHttpLoggingHeadersIgnore: "Authorization"
  atpHttpLoggingUriIgnore: "/rest/deployment/readiness /rest/deployment/liveness /api/tdm/download/csv"
  logLevel: "INFO"
  nodeSelector: {}
  heapDumpEnabled: false
  extraEnvs: []
  storageSize: "1Gi"
  storageClassName: "csi-sc-cinderplugin"
